/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'RssiMsg'
 * message type.
 */

public class RssiMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 12;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 10;

    /** Create a new RssiMsg of size 12. */
    public RssiMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new RssiMsg of the given data_length. */
    public RssiMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiMsg with the given data_length
     * and base offset.
     */
    public RssiMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiMsg using the given byte array
     * as backing store.
     */
    public RssiMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public RssiMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public RssiMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiMsg embedded in the given message
     * at the given base offset.
     */
    public RssiMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiMsg embedded in the given message
     * at the given base offset and length.
     */
    public RssiMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <RssiMsg> \n";
      try {
        s += "  [beacon_id=0x"+Long.toHexString(get_beacon_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [rssi=0x"+Long.toHexString(get_rssi())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [dist="+Float.toString(get_dist())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [mse="+Float.toString(get_mse())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: beacon_id
    //   Field type: int
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'beacon_id' is signed (true).
     */
    public static boolean isSigned_beacon_id() {
        return true;
    }

    /**
     * Return whether the field 'beacon_id' is an array (false).
     */
    public static boolean isArray_beacon_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'beacon_id'
     */
    public static int offset_beacon_id() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'beacon_id'
     */
    public static int offsetBits_beacon_id() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'beacon_id'
     */
    public int get_beacon_id() {
        return (int)getUIntBEElement(offsetBits_beacon_id(), 16);
    }

    /**
     * Set the value of the field 'beacon_id'
     */
    public void set_beacon_id(int value) {
        setUIntBEElement(offsetBits_beacon_id(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'beacon_id'
     */
    public static int size_beacon_id() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'beacon_id'
     */
    public static int sizeBits_beacon_id() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rssi
    //   Field type: short
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rssi' is signed (true).
     */
    public static boolean isSigned_rssi() {
        return true;
    }

    /**
     * Return whether the field 'rssi' is an array (false).
     */
    public static boolean isArray_rssi() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rssi'
     */
    public static int offset_rssi() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rssi'
     */
    public static int offsetBits_rssi() {
        return 16;
    }

    /**
     * Return the value (as a short) of the field 'rssi'
     */
    public short get_rssi() {
        return (short)getSIntBEElement(offsetBits_rssi(), 16);
    }

    /**
     * Set the value of the field 'rssi'
     */
    public void set_rssi(short value) {
        setSIntBEElement(offsetBits_rssi(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'rssi'
     */
    public static int size_rssi() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rssi'
     */
    public static int sizeBits_rssi() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: dist
    //   Field type: float
    //   Offset (bits): 32
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'dist' is signed (true).
     */
    public static boolean isSigned_dist() {
        return true;
    }

    /**
     * Return whether the field 'dist' is an array (false).
     */
    public static boolean isArray_dist() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'dist'
     */
    public static int offset_dist() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'dist'
     */
    public static int offsetBits_dist() {
        return 32;
    }

    /**
     * Return the value (as a float) of the field 'dist'
     */
    public float get_dist() {
        return (float)getFloatElement(offsetBits_dist(), 32);
    }

    /**
     * Set the value of the field 'dist'
     */
    public void set_dist(float value) {
        setFloatElement(offsetBits_dist(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'dist'
     */
    public static int size_dist() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'dist'
     */
    public static int sizeBits_dist() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: mse
    //   Field type: float
    //   Offset (bits): 64
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'mse' is signed (true).
     */
    public static boolean isSigned_mse() {
        return true;
    }

    /**
     * Return whether the field 'mse' is an array (false).
     */
    public static boolean isArray_mse() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'mse'
     */
    public static int offset_mse() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'mse'
     */
    public static int offsetBits_mse() {
        return 64;
    }

    /**
     * Return the value (as a float) of the field 'mse'
     */
    public float get_mse() {
        return (float)getFloatElement(offsetBits_mse(), 32);
    }

    /**
     * Set the value of the field 'mse'
     */
    public void set_mse(float value) {
        setFloatElement(offsetBits_mse(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'mse'
     */
    public static int size_mse() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'mse'
     */
    public static int sizeBits_mse() {
        return 32;
    }

}
